/* Generated By:JavaCC: Do not edit this line. CCGParserConstants.java */
package Reader.CCG;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CCGParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAR = 1;
  /** RegularExpression Id. */
  int SLASH = 2;
  /** RegularExpression Id. */
  int BACKSLASH = 3;
  /** RegularExpression Id. */
  int RPAR = 4;
  /** RegularExpression Id. */
  int S = 5;
  /** RegularExpression Id. */
  int NP = 6;
  /** RegularExpression Id. */
  int N = 7;
  /** RegularExpression Id. */
  int LABEL = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\"/\"",
    "\"\\\\\"",
    "\")\"",
    "\"S\"",
    "\"NP\"",
    "\"N\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<LABEL>",
  };

}
